<?php

return [
    'slugs' => [
        'home' => 'Beranda',
        'donasi' => 'Donasi - Form',
        'donasi-bayar' => 'Donasi - Pembayaran',
        'donasi-sukses' => 'Donasi - Sukses',
        'laporan-odgj' => 'Laporan ODGJ - Form',
        'laporan-odgj-sukses' => 'Laporan ODGJ - Sukses',
        'profil' => 'Profil',
        'profil-struktur' => 'Profil - Struktur Organisasi',
        'profil-visi-misi' => 'Profil - Visi Misi',
        'profil-yayasan' => 'Profil - Yayasan',
        'galeri' => 'Galeri',
        'kontak' => 'Kontak',
        'layanan' => 'Layanan',
        'cara-donasi' => 'Cara Donasi',
        'mitra' => 'Mitra',
        'faq' => 'FAQ',
        'transparansi-donasi' => 'Transparansi Donasi',
        'pasien' => 'Halaman Pasien',
    ],

    'routes' => [
        'welcome' => 'home',
        'donation.form' => 'donasi',
        'donation.payment' => 'donasi-bayar',
        'donation.success' => 'donasi-sukses',
        'odgj-report.form' => 'laporan-odgj',
        'odgj-report.success' => 'laporan-odgj-sukses',
        'pages.profil' => 'profil',
        'profil.struktur' => 'profil-struktur',
        'profil.visi-misi' => 'profil-visi-misi',
        'profil.yayasan' => 'profil-yayasan',
        'pages.galeri' => 'galeri',
        'pages.kontak' => 'kontak',
        'pages.layanan' => 'layanan',
        'pages.cara-donasi' => 'cara-donasi',
        'pages.mitra' => 'mitra',
        'pages.faq' => 'faq',
        'transparansi.donasi' => 'transparansi-donasi',
        'public.pasien.index' => 'pasien',
        'public.pasien.show' => 'pasien',
    ],
];
